import { z } from "zod"; // Import zod if you're using it for validation

// Assuming you have a Zod schema for validation
export const CheckoutSchema = z.object({
  name: z.string(),
  closed: z.boolean(),
  companyId: z.number(),
  currency: z.string(),
  dateInsert: z.string(),
  deliveryAddress: z.string(),
  details: z.string(),
  documentId: z.number(),
  documentStatus: z.number(),
  exchangeRate: z.number().optional().nullable(),
  paymentMethod: z.string(),
  signature: z.string(),
  symbol: z.string(),
  timestamp: z.number(),
  trader: z.string(),
  transport: z.string(),
  orders: z.array(
    z.object({
      orderId: z.number(),
      assortment: z.string(),
      code: z.string(),
      kind: z.string(),
      margin: z.number(),
      price: z.number(),
      netValue: z.number(),
      type: z.string(),
      quantity: z.number(),
      unit: z.string(),
      dateOfRealisation: z.string(),
      productCode: z.string(),
      productId: z.number(),
      postfix: z.string().optional(),
      grossWeight: z.number().optional().nullable(),
      netWeight: z.number().optional().nullable(),
      roller: z.string().optional().nullable(),
      sleeve: z.number().optional().nullable(),
      stretchColor: z.string().optional().nullable(),
      stretchThickness: z.number().optional().nullable(),
      tapeLong: z.number().optional().nullable(),
      tapeWidth: z.number().optional().nullable(),
      tapeThickness: z.number().optional().nullable(),
      numberOfColors: z.number().optional().nullable(),
      glue: z.string().optional().nullable(),
      tapeColor: z.string().optional().nullable(),
      color1: z.string().optional().nullable(),
      color2: z.string().optional().nullable(),
      color3: z.string().optional().nullable(),
      dateOfAcceptation: z.string().optional().nullable(),
      printName: z.string().optional().nullable(),
    })
  ),
});
